use std::{collections::BTreeMap, marker::PhantomData};

use serde_columnar::{
    columnar, from_bytes, iter_from_bytes,
    iterable::{AnyRleIter, DeltaRleIter, GenericIter},
    to_vec,
};

#[columnar(vec, map, ser, de, iterable)]
#[derive(Debug, Clone)]
pub struct Data<'a> {
    #[columnar(strategy = "DeltaRle")]
    a: u32,
    #[columnar(strategy = "Rle")]
    b: String,
    l: PhantomData<&'a ()>,
}

#[columnar(ser, de)]
#[derive(Debug)]
struct VecStore<'a> {
    #[columnar(class = "vec", iter = "Data<'a>")]
    data: Vec<Data<'a>>,
    // #[columnar(class = "map", iter = "(u64, Data)")]
    // map: BTreeMap<u64, Data>,
    id: u32,
}

//================= will be generated by macro

// #[columnar(de)]
// pub struct IterableVecStore<'a> {
//     data: IterableData<'a>,
//     id: u32,
// }

// impl<'de: 'a, 'a> TableIter<'de> for VecStore<'a> {
//     type Iter = IterableVecStore<'de, 'a>;
// }

// #[columnar(de)]
// pub struct IterableData<'i, 'a> {
//     a: DeltaRleIter<'i, u32>,
//     b: AnyRleIter<'i, String>,
//     l: Vec<PhantomData<&'a ()>>,
// }

impl<'de, 'a> Iterator for IterableData<'de, 'a> {
    type Item = Data<'a>;
    fn next(&mut self) -> Option<Self::Item> {
        let next_a = self.a.next();
        let next_b = self.b.next();
        if let (Some(a), Some(b)) = (next_a, next_b) {
            Some(Data {
                a,
                b,
                l: Default::default(),
            })
        } else {
            None
        }
    }
}

fn main() {
    let data = vec![
        Data {
            a: 100,
            b: "a".to_string(),
            l: Default::default(),
        },
        Data {
            a: 101,
            b: "a".to_string(),
            l: Default::default(),
        },
        Data {
            a: 102,
            b: "a".to_string(),
            l: Default::default(),
        },
    ];
    let store = VecStore { data, id: 7 };

    let bytes = to_vec(&store).unwrap();

    println!("encode bytes {:?}", bytes);
    let store: VecStore = from_bytes(&bytes).unwrap();
    println!("store {:?}", store);
    let iter_store = iter_from_bytes::<VecStore>(&bytes);
    // println!("data len {}", iter_store.data.count());
    for data in iter_store.data {
        println!("# {:?}", data)
    }
    assert_eq!(iter_store.id, 7)
}
