[package]
name = "columnar"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
serde = { version = "1.0.147", features = ["derive"] }

[dependencies]
serde_with = "2.0.1"
serde = { version = "1.0.147" }
