[package]
name = "columnar_derive"
version = "0.1.0"

[lib]
name = "columnar_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version="1.0.103",  features=["full", "extra-traits"]}
darling = "0.14.2"
