[package]
name = "loro_columnar"
version = "0.1.0"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
columnar = { version = "0.1.0", path = "../columnar" }

[[example]]
name = "store"