[package]
name = "columnar"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
postcard = "1.0.2"
serde = { version = "1.0.147", features = ["derive"] }
criterion = "0.4"
serde_json = "1.0"

[dependencies]
serde = { version = "1.0"}
postcard = {version="1.0", features=["alloc"]}
thiserror = "1.0"
columnar_derive = { path = "../columnar_derive" }
lazy_static = {version = "1.4", optional = true}
bincode = {version="1.3.3", optional = true}
itertools = "0.10.5"

[[bench]]
name = "columnar_bench"
harness = false

[features]
default = ["bench"]
bench = ["lazy_static", "bincode"]